import { test } from '@playwright/test'
import { card, openApp, tab } from './helpers.ts'

const OUT = process.env.SHOT_DIR ?? 'test-results/shots'

test('Screenshots: gemischte Zustände, Sortiermodus, Dunkelmodus', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Vorlage Oberkörper starten' }).click()
  const first = card(page, 'Aufdehnen seitlich')
  for (const i of [1, 2]) {
    await first.getByLabel(`Satz ${i} Wiederholungen`).fill('12')
    await first.getByRole('button', { name: `Satz ${i} abhaken` }).click()
    await page.getByRole('button', { name: 'Überspringen' }).click()
  }
  const second = card(page, 'Bein absenken (unterer Bauch)')
  await second.getByLabel('Satz 1 Wiederholungen').fill('15')
  await second.getByRole('button', { name: 'Satz 1 abhaken' }).click()
  await page.getByRole('button', { name: '+ Übung' }).click()
  const dialog = page.getByRole('dialog', { name: 'Übungen hinzufügen' })
  await dialog.getByRole('button', { name: 'Kreuzheben', exact: true }).click()
  await dialog.getByRole('button', { name: '1 hinzufügen' }).click()
  await page.screenshot({ path: `${OUT}/10-mixed.png` })
  await page.getByRole('button', { name: 'Überspringen' }).click()
  await page.screenshot({ path: `${OUT}/11-mixed-full.png`, fullPage: true })
  const lat = card(page, 'Lat-Zug')
  await lat.getByRole('button', { expanded: false }).click()
  await lat.scrollIntoViewIfNeeded()
  await page.waitForTimeout(250)
  await page.screenshot({ path: `${OUT}/12-weighted.png` })
  await page.getByRole('button', { name: 'Sortieren' }).click()
  await page.screenshot({ path: `${OUT}/13-sort.png` })
  await page.getByRole('button', { name: 'Fertig' }).click()
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `${OUT}/14-dark.png` })
})

test('Screenshot: Übungsauswahl mit Gruppen', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Freies Training' }).click()
  await page.getByRole('dialog', { name: 'Übungen hinzufügen' }).waitFor()
  await page.screenshot({ path: `${OUT}/15-picker.png` })
})

test('Screenshots: Übungen, Verlauf, Mehr (dunkel)', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Dunklen Modus einschalten' }).click()
  await tab(page, 'Übungen').click()
  await page.screenshot({ path: `${OUT}/16-exercises-dark.png` })
  await page.getByRole('button', { name: 'Lat-Zug' }).click()
  await page.screenshot({ path: `${OUT}/17-exercise-detail-dark.png` })
  await tab(page, 'Mehr').click()
  await page.screenshot({ path: `${OUT}/18-more-dark.png` })
  await page.getByRole('button', { name: 'Hellen Modus einschalten' }).click()
  await page.screenshot({ path: `${OUT}/19-more-light.png` })
})

test('Screenshot: Halteübung als Donut', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Freies Training' }).click()
  const dialog = page.getByRole('dialog', { name: 'Übungen hinzufügen' })
  await dialog.getByRole('button', { name: 'Serratusstütz', exact: true }).click()
  await dialog.getByRole('button', { name: '1 hinzufügen' }).click()
  const c = card(page, 'Serratusstütz')
  await c.getByRole('button', { name: 'Halten starten' }).click()
  await c.getByRole('button', { name: 'Satz fertig' }).click()
  await page.waitForTimeout(1200)
  await c.getByRole('button', { name: 'Pause überspringen' }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: `${OUT}/20-hold-light.png` })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/21-hold-dark.png` })
})

test('Screenshots: Bibliothek (hell/dunkel)', async ({ page }) => {
  await openApp(page)
  await tab(page, 'Übungen').click()
  await page.screenshot({ path: `${OUT}/22-meine-filter.png` })
  await page.getByRole('radio', { name: 'Bibliothek' }).click()
  await page.getByRole('group', { name: 'Ausrüstung' }).getByRole('button', { name: 'Seilzug', exact: true }).click()
  await page.screenshot({ path: `${OUT}/23-library-light.png` })
  await page.getByRole('button', { name: 'Face Pull', exact: true }).click()
  await page.getByRole('list', { name: 'Ausführung' }).waitFor()
  await page.screenshot({ path: `${OUT}/24-library-detail-light.png`, fullPage: true })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/25-library-detail-dark.png`, fullPage: true })
  await page.getByRole('button', { name: '‹ Bibliothek' }).click()
  await page.screenshot({ path: `${OUT}/26-library-dark.png` })
  await page.getByRole('radio', { name: 'Meine' }).click()
  await page.getByRole('group', { name: 'Ausrüstung' }).getByRole('button', { name: 'Alle', exact: true }).click()
  await page.getByRole('button', { name: 'Adduktion', exact: true }).click()
  await page.getByRole('button', { name: 'Bearbeiten' }).click()
  await page.getByText('Zuordnung (Ausrüstung, Muskeln)').click()
  await page.screenshot({ path: `${OUT}/27-form-dark.png` })
})
