import { test } from '@playwright/test'
import { card, openApp, tab } from './helpers.ts'

const OUT = process.env.SHOT_DIR ?? 'test-results/shots'

test('Screenshots: gemischte Zustände, Sortiermodus, Dunkelmodus', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Vorlage Oberkörper starten' }).click()
  const first = card(page, 'Aufdehnen seitlich')
  for (const i of [1, 2]) {
    await first.getByLabel(`Satz ${i} Wiederholungen`).fill('12')
    await first.getByRole('button', { name: `Satz ${i} abhaken` }).click()
    await page.getByRole('button', { name: 'Überspringen' }).click()
  }
  const second = card(page, 'Bein absenken (unterer Bauch)')
  await second.getByLabel('Satz 1 Wiederholungen').fill('15')
  await second.getByRole('button', { name: 'Satz 1 abhaken' }).click()
  await page.getByRole('button', { name: '+ Übung' }).click()
  const dialog = page.getByRole('dialog', { name: 'Übungen hinzufügen' })
  await dialog.getByRole('button', { name: 'Kreuzheben', exact: true }).click()
  await dialog.getByRole('button', { name: '1 hinzufügen' }).click()
  await page.screenshot({ path: `${OUT}/10-mixed.png` })
  await page.getByRole('button', { name: 'Überspringen' }).click()
  await page.screenshot({ path: `${OUT}/11-mixed-full.png`, fullPage: true })
  const lat = card(page, 'Lat-Zug')
  await lat.getByRole('button', { expanded: false }).click()
  await lat.scrollIntoViewIfNeeded()
  await page.waitForTimeout(250)
  await page.screenshot({ path: `${OUT}/12-weighted.png` })
  await page.getByRole('button', { name: 'Sortieren' }).click()
  await page.screenshot({ path: `${OUT}/13-sort.png` })
  await page.getByRole('button', { name: 'Fertig' }).click()
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `${OUT}/14-dark.png` })
})

test('Screenshot: Übungsauswahl mit Gruppen', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Freies Training' }).click()
  await page.getByRole('dialog', { name: 'Übungen hinzufügen' }).waitFor()
  await page.screenshot({ path: `${OUT}/15-picker.png` })
})

test('Screenshots: Übungen, Verlauf, Mehr (dunkel)', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Dunklen Modus einschalten' }).click()
  await tab(page, 'Übungen').click()
  await page.screenshot({ path: `${OUT}/16-exercises-dark.png` })
  await page.getByRole('button', { name: 'Lat-Zug' }).click()
  await page.screenshot({ path: `${OUT}/17-exercise-detail-dark.png` })
  await tab(page, 'Mehr').click()
  await page.screenshot({ path: `${OUT}/18-more-dark.png` })
  await page.getByRole('button', { name: 'Hellen Modus einschalten' }).click()
  await page.screenshot({ path: `${OUT}/19-more-light.png` })
})

test('Screenshot: Halteübung als Donut', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Freies Training' }).click()
  const dialog = page.getByRole('dialog', { name: 'Übungen hinzufügen' })
  await dialog.getByRole('button', { name: 'Serratusstütz', exact: true }).click()
  await dialog.getByRole('button', { name: '1 hinzufügen' }).click()
  const c = card(page, 'Serratusstütz')
  await c.getByRole('button', { name: 'Halten starten' }).click()
  await c.getByRole('button', { name: 'Satz fertig' }).click()
  await page.waitForTimeout(1200)
  await c.getByRole('button', { name: 'Pause überspringen' }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: `${OUT}/20-hold-light.png` })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/21-hold-dark.png` })
})

test('Screenshots: Bibliothek (hell/dunkel)', async ({ page }) => {
  await openApp(page)
  await tab(page, 'Übungen').click()
  await page.screenshot({ path: `${OUT}/22-meine-filter.png` })
  await page.getByRole('radio', { name: 'Bibliothek' }).click()
  await page.getByRole('group', { name: 'Ausrüstung' }).getByRole('button', { name: 'Seilzug', exact: true }).click()
  await page.screenshot({ path: `${OUT}/23-library-light.png` })
  await page.getByRole('button', { name: 'Face Pull', exact: true }).click()
  await page.getByRole('list', { name: 'Ausführung' }).waitFor()
  await page.screenshot({ path: `${OUT}/24-library-detail-light.png`, fullPage: true })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/25-library-detail-dark.png`, fullPage: true })
  await page.getByRole('button', { name: '‹ Bibliothek' }).click()
  await page.screenshot({ path: `${OUT}/26-library-dark.png` })
  await page.getByRole('radio', { name: 'Meine' }).click()
  await page.getByRole('group', { name: 'Ausrüstung' }).getByRole('button', { name: 'Alle', exact: true }).click()
  await page.getByRole('button', { name: 'Adduktion', exact: true }).click()
  await page.getByRole('button', { name: 'Bearbeiten' }).click()
  await page.getByText('Zuordnung (Ausrüstung, Muskeln, Bereiche)').click()
  await page.screenshot({ path: `${OUT}/27-form-dark.png` })
})

test('Screenshots: Programme (hell/dunkel)', async ({ page }) => {
  await openApp(page)
  await page.screenshot({ path: `${OUT}/30-start-teaser.png` })
  await page.getByRole('button', { name: /^Programme/ }).click()
  await page.screenshot({ path: `${OUT}/31-programs.png`, fullPage: true })
  await page.getByRole('listitem', { name: 'Vorschlag Ganzkörper A/B' }).getByRole('button', { name: 'Übernehmen …' }).click()
  await page.screenshot({ path: `${OUT}/32-install.png` })
  await page.getByRole('dialog').getByRole('button', { name: 'Übernehmen und aktivieren' }).click()
  await page.screenshot({ path: `${OUT}/33-hero-light.png` })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/34-hero-dark.png` })
  await page.getByRole('button', { name: 'Anderen Tag wählen' }).click()
  await page.screenshot({ path: `${OUT}/35-daychooser-dark.png` })
  await page.keyboard.press('Escape')
  await page.getByRole('region', { name: /^Programm / }).getByRole('button', { name: 'Programme' }).click()
  await page.getByRole('listitem', { name: 'Ganzkörper A/B' }).getByRole('button', { name: 'Bearbeiten' }).click()
  await page.screenshot({ path: `${OUT}/36-editor-dark.png` })
  await page.getByRole('button', { name: 'Übungen von Ganzkörper B bearbeiten' }).click()
  await page.screenshot({ path: `${OUT}/37-day-dark.png` })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.screenshot({ path: `${OUT}/38-day-light.png` })
})

test('Screenshots: Schonen und Tauschen (hell/dunkel)', async ({ page }) => {
  await openApp(page)
  await tab(page, 'Mehr').click()
  await page.getByRole('button', { name: '+ Bereich schonen' }).click()
  const sheet = page.getByRole('dialog', { name: 'Bereich schonen' })
  await sheet.getByRole('group', { name: 'Körperbereiche' }).getByRole('button', { name: 'Schulter', exact: true }).click()
  await page.screenshot({ path: `${OUT}/40-restrict-sheet.png` })
  await sheet.getByRole('button', { name: 'Schonen', exact: true }).click()
  await page.getByRole('list', { name: 'Geschonte Bereiche' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: `${OUT}/41-restrict-more.png` })
  await tab(page, 'Training').click()
  await page.getByRole('button', { name: 'Vorlage Oberkörper starten' }).click()
  const rb = card(page, 'Reverse Butterfly')
  await rb.getByRole('button', { expanded: false }).click()
  await page.waitForTimeout(400)
  await page.screenshot({ path: `${OUT}/42-banner-light.png` })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: `${OUT}/43-banner-dark.png` })
  await rb.getByRole('button', { name: 'Alternative' }).click()
  await page.screenshot({ path: `${OUT}/44-swap-dark.png` })
})
